#!/usr/bin/env python3
"""
One command to rebuild everything:  python run_all.py

  1. generate   seeded synthetic raw CSVs + answer key + planted-defect log   (skipped if data/raw exists; --regen forces it)
  2. build      raw -> staging -> mart -> metrics in DuckDB
  3. checks     automated data-quality suite -> ops.dq_results   (a critical failure STOPS the run, exit 1)
  4. tests      answer-key, negative, independent pandas recompute  (skip with --skip-tests)
  5. export     metric views -> data/dashboard_data.json
  6. dashboard  docs/index.html (self-contained)
  7. alerts     alerts/weekly_flagged_jobs.md
  8. dictionary docs/data_dictionary.md  and docs/planted_defects.md (regenerated by step 1)
  9. dashboard tests (headless browser) when Playwright is installed (skip with --skip-tests)

Exit codes: 0 success, 1 data-quality failure, 2 any other failure.
SYNTHETIC DATA ONLY.
"""
import argparse
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PY = sys.executable


def step(name, args, ok_codes=(0,), fail_exit=2, quiet=False):
    t = time.time()
    print(f"\n=== {name} ===", flush=True)
    r = subprocess.run([PY, *args], cwd=ROOT, capture_output=quiet, text=True)
    dt = time.time() - t
    if r.returncode not in ok_codes:
        if quiet:
            print((r.stdout or "")[-3000:], (r.stderr or "")[-3000:])
        code = 1 if (name == "data-quality checks" and r.returncode == 1) else fail_exit
        print(f"\nSTOPPED at step '{name}' (exit {r.returncode}) after {dt:.1f}s")
        sys.exit(code)
    print(f"--- {name}: ok ({dt:.1f}s)", flush=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--regen", action="store_true", help="regenerate the synthetic raw data even if it exists")
    ap.add_argument("--skip-tests", action="store_true", help="skip the test suites (faster)")
    a = ap.parse_args()
    t0 = time.time()
    if a.regen or not (ROOT / "data" / "raw" / "projects.csv").exists():
        step("generate synthetic data", ["src/generate_data.py"])
    step("build warehouse", ["src/build_warehouse.py"])
    step("data-quality checks", ["src/run_checks.py"])
    if not a.skip_tests:
        step("test: planted defects and answer key", ["tests/test_planted_defects.py"], quiet=True)
        step("test: checks fail loudly on corrupted data", ["tests/test_checks_fail_loudly.py"], quiet=True)
        step("test: independent pandas recompute", ["tests/independent_recompute.py"], quiet=True)
    step("export dashboard data", ["src/export_dashboard_data.py"])
    step("build dashboard", ["src/build_dashboard.py"])
    step("weekly alerts", ["src/weekly_alerts.py"])
    step("data dictionary", ["src/make_data_dictionary.py"])
    if not a.skip_tests:
        try:
            import playwright  # noqa: F401
            step("test: dashboard in a headless browser", ["tests/test_dashboard.py"], quiet=True)
        except ImportError:
            print("\n(dashboard browser tests skipped: pip install playwright && python -m playwright install chromium)")
    print(f"\nALL DONE in {time.time() - t0:.0f}s.  Open docs/index.html;  alerts in alerts/weekly_flagged_jobs.md")


if __name__ == "__main__":
    main()
